import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const georgia = localFont({
  src: './fonts/georgia.ttf',
  weight: "400",
  preload: true,
  variable: "--font-georgia"
})

const walsheim = localFont({
  src: [
    {
      path: './fonts/GT-Walsheim-Condensed-Light-Trial.otf',
      weight: '300',
      style: 'light',
    },
    {
      path: './fonts/GT-Walsheim-Condensed-Regular-Trial.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/GT-Walsheim-Condensed-Medium-Trial.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/GT-Walsheim-Condensed-Bold-Trial.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: './fonts/GT-Walsheim-Condensed-Black-Trial.otf',
      weight: '900',
      style: 'black',
    },
  ],
  preload: true,
  variable: "--font-walsheim",
  display: "swap"
})


const montserrat = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${walsheim.variable} ${georgia.variable} ${montserrat.variable} bg-black scrollbar-hide no-scrollbar  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
